### ISSUE TITLE
Model.update's options.hooks argument does not work

### ISSUE THREAD

**Issue by celalo** [simpleviewinc/mongolayer#3]
At [Model.js#L730](https://github.com/simpleviewinc/mongolayer/blame/master/Model.js#L730) runtime hooks are check wtih `beforeHooks` key whereas it is supposed to be `hooks` [according to the documentation](https://github.com/simpleviewinc/mongolayer/blame/master/README.md#L1219) and to be consistent with the rest of library.

**Comment by owenallenaz** [comment]
Not only was it referencing the wrong passed in variable, but it was attempting to use beforeFind hooks instead of beforeFilter hooks. I have corrected the issue and published a new version on npm (along with another update). Thanks for reporting.

Closing.
